name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build & push the image, and deploy it to dev
    uses: ./.github/workflows/javascript-workflow.yml
    with:
      enable_build: true
      enable_sync: true
      enable_restart: true
      enable_tag_latest: true
      image_name: ${{ github.event.repository.name }}
      argocd_app: ${{ github.event.repository.name }}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      argocd_host: ${{ secrets.GLOBAL_PUBLIC_ARGOCD_HOST }}
      argocd_password: ${{ secrets.GLOBAL_PUBLIC_ARGOCD_PASSWORD }}
